### ISSUE TITLE
grunt sass is failing

### ISSUE THREAD

**Issue by amanulge** [PredixDev/px-calendar#2]
I am getting this error when I run grunt sass

Running "sass:calendar" (sass) task
>> ".tr" failed to @extend "tr".
>> The selector "tr" was not found.
>> Use "@extend tr !optional" if the extend should be able to fail.
>>   Line 77  Column 3  sass/px-calendar-sketch.scss
Warning:  Use --force to continue.

**Comment by nonmetalhail** [comment]
Hi,
This is not a released component yet and is not functional. Soon....

Please check out the version tags to see what is officially released. If there is a tag, then it has been released.
